[package]
name = "serenity_utils"
version = "0.1.0"
authors = ["AriusX7 <icyligii@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rustls_backend", "cache"]

cache = ["serenity/cache"]
rustls_backend = ["serenity/rustls_backend"]
native_tls_backend = ["serenity/native_tls_backend"]

[dependencies.serenity]
version = "0.9.0-rc.0"
default-features = false
features = ["client", "collector", "gateway", "model"]
